Initial Commit of ansible-galera role
AFCYBER-DREAM/ansible-role-galera pull request #1
Opened 2019-04-19 20:10 UTC by leader716

Initial commit of the ansible-role-galera repo. 

This role will deploy a galera cluster with SSL encryption for the replication. Data at rest encryption will need to be handed by LUKS if that is a requirement.

2019-05-08 13:23 UTC, ragingpastry requested changes
Looks good! Some minor changes requested

2019-05-08 13:23 UTC, ragingpastry commented on molecule/default/requirements.yml
> +- src: git+https://github.com/leader716/ansible-role-repositories.git
These should probably point to `afcyber-dream` instead of `leader716`. If we are waiting on modifications to upstream on those repositories then lets get those merged first before accepting this

2019-05-08 13:23 UTC, ragingpastry commented on molecule/default/requirements.yml
> +  version: jward-role-security
Same here

2019-05-08 13:23 UTC, ragingpastry commented on molecule/default/requirements.yml
> +- src: git+https://github.com/leader716/ansible-role-packages.git
Same here

2019-05-08 13:23 UTC, ragingpastry commented on molecule/default/tests/test_default.py
> +    assert f.group == 'root'
We should have some barebones tests for this first. Maybe we could use testinfra to ensure that the service is running, packages are installed, selinux policy is found, and a database connection can be made

2019-05-08 13:23 UTC, ragingpastry commented on README.md
> +
Do we want to document that `gather_facts` is required? Unsure about this one

2019-05-13 12:35 UTC, leader716 commented on molecule/default/requirements.yml
> +- src: git+https://github.com/leader716/ansible-role-repositories.git
Since we now have the other repos merged, I have updated these to point to the proper repos

2019-05-13 12:52 UTC, ragingpastry approved these changes
lgtm

2019-05-13 12:54 UTC, merged